"""Store the curated English inflection data used by variant expansion."""

# This map covers the common irregular verb families allowed by default.
IRREGULAR_FAMILIES: dict[str, tuple[str, ...]] = {
    "be": ("am", "is", "are", "was", "were", "being", "been"),
    "become": ("becomes", "becoming", "became"),
    "begin": ("begins", "beginning", "began", "begun"),
    "break": ("breaks", "breaking", "broke", "broken"),
    "bring": ("brings", "bringing", "brought"),
    "build": ("builds", "building", "built"),
    "buy": ("buys", "buying", "bought"),
    "choose": ("chooses", "choosing", "chose", "chosen"),
    "come": ("comes", "coming", "came"),
    "cut": ("cuts", "cutting"),
    "do": ("does", "doing", "did", "done"),
    "drink": ("drinks", "drinking", "drank", "drunk"),
    "drive": ("drives", "driving", "drove", "driven"),
    "eat": ("eats", "eating", "ate", "eaten"),
    "fall": ("falls", "falling", "fell", "fallen"),
    "feel": ("feels", "feeling", "felt"),
    "fight": ("fights", "fighting", "fought"),
    "find": ("finds", "finding", "found"),
    "fly": ("flies", "flying", "flew", "flown"),
    "get": ("gets", "getting", "got", "gotten"),
    "give": ("gives", "giving", "gave", "given"),
    "go": ("goes", "going", "went", "gone"),
    "grow": ("grows", "growing", "grew", "grown"),
    "have": ("has", "having", "had"),
    "hear": ("hears", "hearing", "heard"),
    "hold": ("holds", "holding", "held"),
    "keep": ("keeps", "keeping", "kept"),
    "know": ("knows", "knowing", "knew", "known"),
    "leave": ("leaves", "leaving", "left"),
    "lead": ("leads", "leading", "led"),
    "lose": ("loses", "losing", "lost"),
    "make": ("makes", "making", "made"),
    "mean": ("means", "meaning", "meant"),
    "meet": ("meets", "meeting", "met"),
    "pay": ("pays", "paying", "paid"),
    "plan": ("plans", "planning", "planned"),
    "put": ("puts", "putting"),
    "read": ("reads", "reading"),
    "rise": ("rises", "rising", "rose", "risen"),
    "run": ("runs", "running", "ran"),
    "say": ("says", "saying", "said"),
    "see": ("sees", "seeing", "saw", "seen"),
    "sell": ("sells", "selling", "sold"),
    "send": ("sends", "sending", "sent"),
    "set": ("sets", "setting"),
    "show": ("shows", "showing", "showed", "shown"),
    "sit": ("sits", "sitting", "sat"),
    "sleep": ("sleeps", "sleeping", "slept"),
    "speak": ("speaks", "speaking", "spoke", "spoken"),
    "stand": ("stands", "standing", "stood"),
    "take": ("takes", "taking", "took", "taken"),
    "teach": ("teaches", "teaching", "taught"),
    "tell": ("tells", "telling", "told"),
    "think": ("thinks", "thinking", "thought"),
    "win": ("wins", "winning", "won"),
    "write": ("writes", "writing", "wrote", "written"),
}

# This map covers the irregular noun plurals allowed by default.
IRREGULAR_NOUNS: dict[str, tuple[str, ...]] = {
    "child": ("children",),
    "foot": ("feet",),
    "man": ("men",),
    "mouse": ("mice",),
    "person": ("people",),
    "tooth": ("teeth",),
    "woman": ("women",),
}

# These regular verbs get conservative automatic inflection support.
AUTO_VERB_BASES = {
    "accept",
    "act",
    "add",
    "agree",
    "answer",
    "appear",
    "argue",
    "arrive",
    "ask",
    "attack",
    "believe",
    "call",
    "change",
    "compare",
    "consider",
    "continue",
    "control",
    "cook",
    "create",
    "damage",
    "decide",
    "demand",
    "deny",
    "die",
    "end",
    "enjoy",
    "explain",
    "follow",
    "force",
    "forgive",
    "gain",
    "happen",
    "help",
    "hope",
    "improve",
    "include",
    "increase",
    "influence",
    "join",
    "jump",
    "kill",
    "learn",
    "like",
    "listen",
    "live",
    "look",
    "love",
    "move",
    "need",
    "offer",
    "open",
    "plan",
    "play",
    "pull",
    "push",
    "remain",
    "remember",
    "report",
    "require",
    "return",
    "seem",
    "serve",
    "start",
    "stay",
    "study",
    "talk",
    "travel",
    "try",
    "turn",
    "use",
    "wait",
    "walk",
    "want",
    "watch",
    "work",
}

# These regular nouns get conservative plural support.
AUTO_NOUN_BASES = {
    "area",
    "body",
    "boy",
    "business",
    "car",
    "case",
    "child",
    "city",
    "company",
    "country",
    "day",
    "door",
    "face",
    "fact",
    "family",
    "field",
    "force",
    "form",
    "girl",
    "government",
    "group",
    "head",
    "home",
    "hour",
    "house",
    "kind",
    "law",
    "line",
    "member",
    "month",
    "name",
    "nation",
    "number",
    "office",
    "order",
    "part",
    "period",
    "place",
    "point",
    "power",
    "president",
    "problem",
    "program",
    "question",
    "reason",
    "result",
    "room",
    "school",
    "service",
    "side",
    "street",
    "system",
    "thing",
    "time",
    "value",
    "war",
    "water",
    "way",
    "week",
    "word",
    "world",
    "year",
}

# These verbs double the final consonant in the derived regular forms.
DOUBLE_FINAL_CONSONANT_VERBS = {
    "drop",
    "plan",
    "ship",
    "shop",
    "slip",
    "step",
    "stop",
    "trip",
}

# These words should never receive automatic noun-style pluralization.
NON_INFLECTING_WORDS = {
    "a",
    "all",
    "also",
    "an",
    "and",
    "any",
    "as",
    "at",
    "be",
    "but",
    "by",
    "for",
    "from",
    "he",
    "i",
    "if",
    "in",
    "it",
    "may",
    "more",
    "most",
    "must",
    "no",
    "not",
    "of",
    "on",
    "or",
    "other",
    "our",
    "she",
    "so",
    "some",
    "than",
    "that",
    "the",
    "their",
    "them",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "through",
    "to",
    "up",
    "us",
    "we",
    "what",
    "when",
    "which",
    "who",
    "with",
    "would",
    "you",
}
